# Pearson's Chi-Square Test 

Chi-Square Test is used to determine whether there is a statistically significant difference between the expected frequencies and the observed frequencies in one or more categories of a contingency table.  In other words it also determines whether there is an association between categorical variables (i.e., whether the variables are independent or related). It is a nonparametric test.

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("C:\\Users\\karth\\Desktop\\chi.csv") 

In [4]:
data

Gender       Trip
0     Male  Trekking 
1     Male  Trekking 
2     Male      Beach
3   Female  Trekking 
4   Female      Beach
5     Male  Trekking 
6     Male  Trekking 
7     Male      Beach
8   Female      Beach
9   Female  Trekking 
10    Male  Trekking 
11  Female      Beach
12    Male  Trekking 
13  Female  Trekking 
14    Male  Trekking 
15    Male      Beach
16    Male  Trekking 
17  Female      Beach
18  Female      Beach
19    Male  Trekking 
20  Female  Trekking 
21    Male      Beach
22  Female  Trekking 
23    Male      Beach
24    Male  Trekking 
25  Female      Beach
26  Female  Trekking 
27    Male      Beach
28  Female      Beach
29    Male  Trekking 
30  Female      Beach
31    Male      Beach
32    Male      Beach
33    Male      Beach
34  Female  Trekking 
35    Male      Beach
36  Female  Trekking 
37  Female      Beach
38  Female      Beach
39    Male  Trekking 
40    Male      Beach
41  Female      Beach
42  Female      Beach
43    Male  Trekking 
44    Male      Beach
45    Male  Trekking 
46  Female  Trekking 
47    Male      Beach
48  Female  Trekking 
49    Male  Trekking

In [5]:
data_table = pd.crosstab(data['Gender'], data['Trip'])
print(data_table)

Trip    Beach  Trekking 
Gender                  
Female     12         10
Male       13         15


In [6]:
data_table.values

array([[12, 10],
       [13, 15]], dtype=int64)

In [7]:
#Observed Values
observed_value = data_table.values 
print("Observed Values :\n",observed_value)

Observed Values :
 [[12 10]
 [13 15]]


In [8]:
import scipy.stats as stats
exp_val=stats.chi2_contingency(data_table)

In [9]:
#expected value
exp_val

(0.08116883116883117,
 0.7757196518444691,
 1,
 array([[11., 11.],
        [14., 14.]]))

In [10]:
expected_value = exp_val[3]

In [11]:
expected_value

array([[11., 11.],
       [14., 14.]])

In [12]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_value,expected_value)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [13]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.3246753246753247


In [14]:
#calculating degree of freedom 
no_of_rows=len(data_table.iloc[0:2,0])
no_of_columns=len(data_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [15]:
tabular_value=chi2.ppf(q=1-alpha,df=ddof)
print('tabular_value/critical value:',tabular_value)

tabular_value/critical value: 3.841458820694124


In [16]:
if chi_square_statistic>=tabular_value:
    print("Accept Alternate Hypothesis. There is a relationship between 2 categorical variables")
else:
    print("Accept Null Hypothesis, There is no significant relationship between 2 categorical variables")

Accept Null Hypothesis, There is no significant relationship between 2 categorical variables
